apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: order-app   
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30090
