apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ['sh','-c','until nc -z mysql-service 3306; do echo "waiting for mysql..."; sleep 2; done']
      containers:
        - name: order-app
          image: dhiac7/order-app:latest
          imagePullPolicy: Always
          env:
            - name: HEADLESS
              value: "1"
            - name: PORT
              value: "8080"
            - name: DB_URL
              value: "jdbc:mysql://mysql-service:3306/javafxdb?useSSL=false&allowPublicKeyRetrieval=true"
            - name: DB_USER
              value: "javafxuser"
            - name: DB_PASS
              value: "javafxpass"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }

