apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  namespace: devops
  labels:
    app: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
        - name: order-app
          image: dhiac7/order-app:latest   
          ports:
            - containerPort: 8080
