apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30091

